<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique(); // Generated by the tablet
            $table->foreignId('user_id')->nullable()->constrained()->onDelete('set null'); // Cashier
            $table->unsignedBigInteger('sequence_number'); // Sequential ticket number

            // Financial details (HT / TVA / TTC)
            $table->decimal('subtotal_excl_vat', 10, 2);
            $table->decimal('vat_amount', 10, 2);
            $table->decimal('total_incl_vat', 10, 2);

            // Crypto signing (Loi Anti-Fraude TVA)
            $table->string('hash', 64)->nullable();
            $table->string('previous_hash', 64)->nullable();

            $table->string('status')->default('completed');
            $table->timestamp('completed_at');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('orders');
    }
};
